package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.01 19:13:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoitusTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi57 */
  @Test
  public void testRekisteroi57() {    // Harjoitus: 57
    Harjoitus l1 = new Harjoitus(); 
    assertEquals("From: Harjoitus line: 59", 0, l1.getharj_id()); 
    Harjoitus l2 = new Harjoitus(); 
    int n1 = l1.getharj_id(); 
    int n2 = l2.getharj_id(); 
    assertEquals("From: Harjoitus line: 63", n2-1, n1); 
  } // Generated by ComTest END
}