package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.02 15:10:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoituksetTest {



  // Generated by ComTest BEGIN
  /** testAnna23 */
  @Test
  public void testAnna23() {    // Harjoitukset: 23
    var h = new Harjoitukset(); 
    h.lisaa(new Harjoitus()); 
    h.lisaa(new Harjoitus()); 
    h.lisaa(new Harjoitus()); 
    h.lisaa(new Harjoitus()); 
    assertEquals("From: Harjoitukset line: 29", 4, h.getlkm()); 
    assertEquals("From: Harjoitukset line: 30", 3, h.annaID(3).getharj_id()); 
    assertEquals("From: Harjoitukset line: 31", true, h.poista(3)); 
    assertEquals("From: Harjoitukset line: 32", false, h.poista(3)); 
    assertEquals("From: Harjoitukset line: 33", 3, h.getlkm()); 
    try {
    h.anna(3); 
    fail("Harjoitukset: 34 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}