package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.07 17:05:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoituksienSisaltoTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnna29 
   * @throws SailoException when error
   */
  @Test
  public void testAnna29() throws SailoException {    // HarjoituksienSisalto: 29
    var h = new HarjoituksienSisalto(); 
    h.lisaa(new HarjoituksenSisalto()); 
    h.lisaa(new HarjoituksenSisalto()); 
    h.lisaa(new HarjoituksenSisalto()); 
    h.lisaa(new HarjoituksenSisalto()); 
    assertEquals("From: HarjoituksienSisalto line: 36", 4, h.getlkm()); 
    assertEquals("From: HarjoituksienSisalto line: 37", 1, h.anna(3).get_id()-h.anna(2).get_id()); 
    try {
    h.anna(4); 
    fail("HarjoituksienSisalto: 38 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista68 */
  @Test
  public void testPoista68() {    // HarjoituksienSisalto: 68
    var hs = new HarjoituksienSisalto(); 
    hs.lisaa(new HarjoituksenSisalto("1|1|1|1|1|1")); 
    hs.lisaa(new HarjoituksenSisalto("2|1|1|1|1|1")); 
    hs.lisaa(new HarjoituksenSisalto("3|1|1|1|1|1")); 
    assertEquals("From: HarjoituksienSisalto line: 73", 3, hs.getlkm()); 
    assertEquals("From: HarjoituksienSisalto line: 74", true, hs.poista(1)); 
    assertEquals("From: HarjoituksienSisalto line: 75", 2, hs.getlkm()); 
    assertEquals("From: HarjoituksienSisalto line: 76", 2, hs.poistaKaikki(1)); 
    assertEquals("From: HarjoituksienSisalto line: 77", 0, hs.getlkm()); 
  } // Generated by ComTest END
}