package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.02 15:11:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoitusTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi53 */
  @Test
  public void testRekisteroi53() {    // Harjoitus: 53
    Harjoitus l1 = new Harjoitus(); 
    Harjoitus l2 = new Harjoitus(); 
    int n1 = l1.getharj_id(); 
    int n2 = l2.getharj_id(); 
    assertEquals("From: Harjoitus line: 58", n2-1, n1); 
  } // Generated by ComTest END
}