package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.07 16:10:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoituksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnna29 
   * @throws SailoException when error
   */
  @Test
  public void testAnna29() throws SailoException {    // Harjoitukset: 29
    var h = new Harjoitukset(); 
    h.lisaa(new Harjoitus()); 
    h.lisaa(new Harjoitus()); 
    h.lisaa(new Harjoitus()); 
    h.lisaa(new Harjoitus()); 
    assertEquals("From: Harjoitukset line: 36", 4, h.getlkm()); 
    assertEquals("From: Harjoitukset line: 37", 3, h.annaHarjoitus(3).getharj_id()); 
    assertEquals("From: Harjoitukset line: 38", true, h.poista(3)); 
    assertEquals("From: Harjoitukset line: 39", false, h.poista(3)); 
    assertEquals("From: Harjoitukset line: 40", 3, h.getlkm()); 
    try {
    h.anna(3); 
    fail("Harjoitukset: 41 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}