package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.17 12:03:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnnaLiike92 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaLiike92() throws SailoException {    // Liikkeet: 92
    Liikkeet l = new Liikkeet(); 
    l.lisaa(new Liike("kuperkeikka",true)); 
    assertEquals("From: Liikkeet line: 96", "kuperkeikka", l.annaLiike(1).getLiikkeenNimi()); 
    try {
    l.annaLiike(2); 
    fail("Liikkeet: 97 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    l.lisaa(new Liike("karrynpyora", true)); 
    assertEquals("From: Liikkeet line: 99", "karrynpyora", l.annaLiike(2).getLiikkeenNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testOnkoUusi169 
   * @throws SailoException when error
   */
  @Test
  public void testOnkoUusi169() throws SailoException {    // Liikkeet: 169
    Liikkeet l = new Liikkeet(); 
    l.lisaa(new Liike("kuperkeikka",true)); 
    assertEquals("From: Liikkeet line: 173", false, l.onkoUusi("kuperkeikka")); 
    assertEquals("From: Liikkeet line: 174", false, l.onkoUusi(" Kuperkeikka  ")); 
    assertEquals("From: Liikkeet line: 175", true, l.onkoUusi("kuperke ikka")); 
  } // Generated by ComTest END
}