package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.01 18:24:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testParse55 */
  @Test
  public void testParse55() {    // Liike: 55
    Liike l1 = new Liike(); 
    l1.parse("3|kuperkeikka"); 
    assertEquals("From: Liike line: 58", "kuperkeikka", l1.getLiikkeenNimi()); 
    assertEquals("From: Liike line: 59", 3, l1.getLiike_id()); 
    l1.parse(""); 
    assertEquals("From: Liike line: 61", "VirheellinenTallennusmuoto", l1.getLiikkeenNimi()); 
    assertEquals("From: Liike line: 62", -1, l1.getLiike_id()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi96 */
  @Test
  public void testRekisteroi96() {    // Liike: 96
    Liike l1 = new Liike(); 
    assertEquals("From: Liike line: 98", 0, l1.getLiike_id()); 
    l1.rekisteroi(); 
    Liike l2 = new Liike(); 
    l2.rekisteroi(); 
    int n1 = l1.getLiike_id(); 
    int n2 = l2.getLiike_id(); 
    assertEquals("From: Liike line: 104", n2-1, n1); 
  } // Generated by ComTest END
}