package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.24 10:57:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testParse48 */
  @Test
  public void testParse48() {    // Liike: 48
    Liike l1 = new Liike(); 
    l1.parse("15|kuperkeikka"); 
    assertEquals("From: Liike line: 51", "kuperkeikka", l1.getLiikkeenNimi()); 
    assertEquals("From: Liike line: 52", 15, l1.getLiike_id()); 
    Liike l2 = new Liike(); 
    assertEquals("From: Liike line: 54", 1, l2.getLiike_id()-l1.getLiike_id()); 
    l1.parse(""); 
    assertEquals("From: Liike line: 56", "VirheellinenTallennusmuoto", l1.getLiikkeenNimi()); 
    assertEquals("From: Liike line: 57", -1, l1.getLiike_id()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi103 */
  @Test
  public void testRekisteroi103() {    // Liike: 103
    Liike l1 = new Liike(); 
    Liike l2 = new Liike(); 
    int n1 = l1.getLiike_id(); 
    int n2 = l2.getLiike_id(); 
    assertEquals("From: Liike line: 108", n2-1, n1); 
  } // Generated by ComTest END
}