package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.02 15:14:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** testAnnaLiike84 */
  @Test
  public void testAnnaLiike84() {    // Liikkeet: 84
    Liikkeet l = new Liikkeet(); 
    l.lisaa(new Liike("kuperkeikka",true)); 
    assertEquals("From: Liikkeet line: 87", "kuperkeikka", l.annaLiike(1).getLiikkeenNimi()); 
    try {
    l.annaLiike(2); 
    fail("Liikkeet: 88 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    l.lisaa(new Liike("karrynpyora", true)); 
    assertEquals("From: Liikkeet line: 90", "karrynpyora", l.annaLiike(2).getLiikkeenNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoUusi136 */
  @Test
  public void testOnkoUusi136() {    // Liikkeet: 136
    Liikkeet l = new Liikkeet(); 
    l.lisaa(new Liike("kuperkeikka",true)); 
    assertEquals("From: Liikkeet line: 139", false, l.onkoUusi("kuperkeikka")); 
    assertEquals("From: Liikkeet line: 140", false, l.onkoUusi(" Kuperkeikka  ")); 
    assertEquals("From: Liikkeet line: 141", true, l.onkoUusi("kuperke ikka")); 
  } // Generated by ComTest END
}