package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.01 19:06:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** testAnnaLiike84 */
  @Test
  public void testAnnaLiike84() {    // Liikkeet: 84
    Liikkeet l = new Liikkeet(); 
    l.lisaa(new Liike("kuperkeikka",true)); 
    assertEquals("From: Liikkeet line: 87", "kuperkeikka", l.annaLiike(1).getLiikkeenNimi()); 
    assertEquals("From: Liikkeet line: 88", null, l.annaLiike(2)); 
    l.lisaa(new Liike("karrynpyora", true)); 
    assertEquals("From: Liikkeet line: 90", "karrynpyora", l.annaLiike(2).getLiikkeenNimi()); 
  } // Generated by ComTest END
}