package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.04 12:13:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SpvkTest {



  // Generated by ComTest BEGIN
  /** 
   * testLiikeHistoriaTiedostona167 
   * @throws SailoException when error
   */
  @Test
  public void testLiikeHistoriaTiedostona167() throws SailoException {    // Spvk: 167
    Spvk spvk = new Spvk(); 
    spvk.lisaa(new Liike("kuperkeikka",true)); 
    spvk.lisaa(new Liike("karrynpyora",true)); 
    spvk.lisaa(new Harjoitus("3.4.2019",true)); 
    spvk.lisaa(new Harjoitus("1.4.2019",true)); 
    spvk.lisaa(new Harjoitus("5.4.2019",true)); 
    int[] t1 = { 2,1,3,12,65} ; 
    int[] t2 = { 1,2,4,4,40} ; 
    int[] t3 = { 1,1,5,9,120} ; 
    int[] t4 = { 3,1,3,8,75} ; 
    spvk.lisaa(new HarjoituksenSisalto(t1)); 
    spvk.lisaa(new HarjoituksenSisalto(t2)); 
    spvk.lisaa(new HarjoituksenSisalto(t3)); 
    spvk.lisaa(new HarjoituksenSisalto(t4)); 
    assertEquals("From: Spvk line: 183", 51, spvk.liikeHistoriaTiedostona(1).length()); 
    assertEquals("From: Spvk line: 184", 40, spvk.harjsisTiedostona(1).length()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaHarjoitus234 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaHarjoitus234() throws SailoException {    // Spvk: 234
    Spvk spvk = new Spvk(); 
    var h =  new Harjoitus("1.2.2020", true); 
    var hs = new HarjoituksenSisalto("1|1|1|1|1|1"); 
    spvk.lisaa(h); 
    spvk.lisaa(hs); 
    assertEquals("From: Spvk line: 241", 1, spvk.getHarjsislkm()); 
    spvk.poistaHarjoitus(h.getID()); 
    assertEquals("From: Spvk line: 243", 0, spvk.getHarjoitustenlkm()); 
    assertEquals("From: Spvk line: 244", 0, spvk.getHarjsislkm()); 
  } // Generated by ComTest END
}