package salipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import salipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.24 12:13:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SpvkTest {



  // Generated by ComTest BEGIN
  /** 
   * testLiikeHistoriaTiedostona172 
   * @throws SailoException when error
   */
  @Test
  public void testLiikeHistoriaTiedostona172() throws SailoException {    // Spvk: 172
    Spvk spvk = new Spvk(); 
    spvk.lisaa(new Liike("kuperkeikka",true)); 
    spvk.lisaa(new Liike("karrynpyora",true)); 
    spvk.lisaa(new Harjoitus("3.4.2019",true)); 
    spvk.lisaa(new Harjoitus("1.4.2019",true)); 
    spvk.lisaa(new Harjoitus("5.4.2019",true)); 
    int[] t1 = { 2,1,3,12,65} ; 
    int[] t2 = { 1,2,4,4,40} ; 
    int[] t3 = { 1,1,5,9,120} ; 
    int[] t4 = { 3,1,3,8,75} ; 
    spvk.lisaa(new HarjoituksenSisalto(t1)); 
    spvk.lisaa(new HarjoituksenSisalto(t2)); 
    spvk.lisaa(new HarjoituksenSisalto(t3)); 
    spvk.lisaa(new HarjoituksenSisalto(t4)); 
    assertEquals("From: Spvk line: 188", 51, spvk.liikeHistoriaTiedostona(1).length()); 
    assertEquals("From: Spvk line: 189", 40, spvk.harjsisTiedostona(1).length()); 
  } // Generated by ComTest END
}