package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.Pvm.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.07 17:04:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testTarkistaPvm21 */
  @Test
  public void testTarkistaPvm21() {    // Pvm: 21
    assertEquals("From: Pvm line: 22", null, TarkistaPvm("3.4.2020")); 
    assertEquals("From: Pvm line: 23", "vuosi puuttuu tai on virheellinen", TarkistaPvm("3.4")); 
    assertEquals("From: Pvm line: 24", null, TarkistaPvm("29.2.2020")); 
    assertEquals("From: Pvm line: 25", "päivä virheellinen", TarkistaPvm("29.2.2019")); 
  } // Generated by ComTest END
}